name: Create Kubernetes Namespace

on:
  workflow_dispatch:
    inputs:
      _entity_environment_spec_resourceGroup:
        description: Environment Resource Group
        type: string
        required: false
      _entity_environment_spec_subscription:
        description: Environment Subscription
        type: string
        required: false
      _entity_environment_spec_clusterName:
        description: The name of the cluster in which to create the namespace
        type: string
        required: false


env:
  description: This workflow is used to create a Kubernetes namespace

permissions:
  id-token: write
  contents: read

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - name: InputSummary
        run: |
          echo "### Inputs" >> $GITHUB_STEP_SUMMARY
          echo "| input | value |" >> $GITHUB_STEP_SUMMARY
          echo "| ----- | ----- |" >> $GITHUB_STEP_SUMMARY
          echo "| _entity_environment_spec_ResourceGroup | ${{ inputs._entity_environment_spec_ResourceGroup }} |" >> $GITHUB_STEP_SUMMARY
          echo "| _entity_environment_spec_Subscription | ${{ inputs._entity_environment_spec_Subscription }} |" >> $GITHUB_STEP_SUMMARY
          echo "| _entity_environment_spec_clusterName | ${{ inputs._entity_environment_spec_clusterName }} |" >> $GITHUB_STEP_SUMMARY

      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ inputs._entity_environment_spec_subscription }}

      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ inputs._entity_environment_spec_resourceGroup }}
          cluster-name: ${{ inputs._entity_environment_spec_clusterName }}

      - name: Apply
        run: kubectl apply -f manifests/namespace.yml
